name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH Run Commands on Windows VPS
        uses: appleboy/ssh-action@master
        with:
          host: 38.109.113.107
          username: administrator
          script: |
            cd C:\websites\skmiraj\storeManagementProject
            git reset --hard HEAD
            git pull origin master
