name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start SSH Agent
        run: |
          eval "$(ssh-agent)"
           ssh-add "C:\Users\Administrator\.ssh\id_rsa"

      - name: Deploy to Windows VPS
        uses: appleboy/scp-action@master
        with:
          host: 38.109.113.107
          username: administrator
          source: ./
          target: 'C:\websites\skmiraj\storeManagementProject'

      - name: SSH Run Commands on Windows VPS
        uses: appleboy/ssh-action@master
        with:
          host: 38.109.113.107
          username: administrator
          script: |
            cd C:\websites\skmiraj\storeManagementProject
            git reset --hard HEAD
            git pull origin master
