name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Files on Windows VPS using Git Bash Script
        shell: bash
        run: |

          cd C:/websites/skmiraj/storeManagementProject

          git reset --hard HEAD

          git pull origin master
