name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Files on Windows VPS
        run: |
          # Navigate to the project directory
          cd C:\websites\skmiraj\storeManagementProject

          # Reset any changes in the repository
          git reset --hard HEAD

          # Pull the latest changes from the master branch -s
          git pull origin master